name = "sharewatt-simulator"
main = "dist/simple-server.js"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
FRONTEND_URL = "https://your-frontend-domain.pages.dev"

# Workers configuration
[env.production]
name = "sharewatt-simulator-prod"

[env.staging]
name = "sharewatt-simulator-staging"
